apiVersion: v1
kind: Namespace
metadata:
  name: aichat

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nai-chatapp-deployment
  namespace: aichat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nai-chatapp
  template:
    metadata:
      labels:
        app: nai-chatapp
    spec:
      containers:
        - name: nai-chatapp
          image: johnugeorge/nai-chatapp:0.12
          ports:
            - containerPort: 8502
          volumeMounts:
            - name: chat-data
              mountPath: /mnt/data/chat
      volumes:
        - name: chat-data
          persistentVolumeClaim:
            claimName: nai-chatapp-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nai-chatapp-pvc
  namespace: aichat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nutanix-volume

---

apiVersion: v1
kind: Service
metadata:
  name: nai-chatapp-service
  namespace: aichat
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8502
  selector:
    app: nai-chatapp

---

apiVersion: networking.k8s.io/v1
kind: Ingress
  name: nai-chatapp-ingress
  namespace: aichat
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "false"
spec:
  tls:
  - hosts:
    - chat.utech.local
  rules: 
  - host: chat.utech.local
    http:
      paths:
      - path: /
        backend:
          service:
            name: nai-chatapp-service
            port:
              number: 8080