apiVersion: v1
kind: Namespace
metadata:
  name: cs-inference
  labels:
    app.kubernetes.io/part-of: cs-agent-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: cs-pipeline
  labels:
    app.kubernetes.io/part-of: cs-agent-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: cs-agent
  labels:
    app.kubernetes.io/part-of: cs-agent-demo
